import UIKit

// Generated by 'Automation/update_colors.py'
public extension UIColor {

    // MARK: - Blue
    /// Zuper Blue Dark color.
    static var blueDark = fromResource(named: "Blue Dark")
    /// Zuper Blue Dark Active color.
    static var blueDarkActive = fromResource(named: "Blue Dark Active")
    /// Zuper Blue Dark Hover color.
    static var blueDarkHover = fromResource(named: "Blue Dark Hover")
    /// Zuper Blue Light color.
    static var blueLight = fromResource(named: "Blue Light")
    /// Zuper Blue Light Active color.
    static var blueLightActive = fromResource(named: "Blue Light Active")
    /// Zuper Blue Light Hover color.
    static var blueLightHover = fromResource(named: "Blue Light Hover")
    /// Zuper Blue Normal color.
    static var blueNormal = fromResource(named: "Blue Normal")
    /// Zuper Blue Normal Active color.
    static var blueNormalActive = fromResource(named: "Blue Normal Active")
    /// Zuper Blue Normal Hover color.
    static var blueNormalHover = fromResource(named: "Blue Normal Hover")

    // MARK: - Bundle
    /// Zuper Bundle Basic color.
    static var bundleBasic = fromResource(named: "Bundle Basic")
    /// Zuper Bundle Medium color.
    static var bundleMedium = fromResource(named: "Bundle Medium")

    // MARK: - Cloud
    /// Zuper Cloud Dark color.
    static var cloudDark = fromResource(named: "Cloud Dark")
    /// Zuper Cloud Dark Active color.
    static var cloudDarkActive = fromResource(named: "Cloud Dark Active")
    /// Zuper Cloud Dark Hover color.
    static var cloudDarkHover = fromResource(named: "Cloud Dark Hover")
    /// Zuper Cloud Light color.
    static var cloudLight = fromResource(named: "Cloud Light")
    /// Zuper Cloud Light Active color.
    static var cloudLightActive = fromResource(named: "Cloud Light Active")
    /// Zuper Cloud Light Hover color.
    static var cloudLightHover = fromResource(named: "Cloud Light Hover")
    /// Zuper Cloud Normal color.
    static var cloudNormal = fromResource(named: "Cloud Normal")
    /// Zuper Cloud Normal Active color.
    static var cloudNormalActive = fromResource(named: "Cloud Normal Active")
    /// Zuper Cloud Normal Hover color.
    static var cloudNormalHover = fromResource(named: "Cloud Normal Hover")

    // MARK: - Green
    /// Zuper Green Dark color.
    static var greenDark = fromResource(named: "Green Dark")
    /// Zuper Green Dark Active color.
    static var greenDarkActive = fromResource(named: "Green Dark Active")
    /// Zuper Green Dark Hover color.
    static var greenDarkHover = fromResource(named: "Green Dark Hover")
    /// Zuper Green Light color.
    static var greenLight = fromResource(named: "Green Light")
    /// Zuper Green Light Active color.
    static var greenLightActive = fromResource(named: "Green Light Active")
    /// Zuper Green Light Hover color.
    static var greenLightHover = fromResource(named: "Green Light Hover")
    /// Zuper Green Normal color.
    static var greenNormal = fromResource(named: "Green Normal")
    /// Zuper Green Normal Active color.
    static var greenNormalActive = fromResource(named: "Green Normal Active")
    /// Zuper Green Normal Hover color.
    static var greenNormalHover = fromResource(named: "Green Normal Hover")

    // MARK: - Ink
    /// Zuper Ink Dark color.
    static var inkDark = fromResource(named: "Ink Dark")
    /// Zuper Ink Dark Active color.
    static var inkDarkActive = fromResource(named: "Ink Dark Active")
    /// Zuper Ink Dark Hover color.
    static var inkDarkHover = fromResource(named: "Ink Dark Hover")
    /// Zuper Ink Light color.
    static var inkLight = fromResource(named: "Ink Light")
    /// Zuper Ink Light Active color.
    static var inkLightActive = fromResource(named: "Ink Light Active")
    /// Zuper Ink Light Hover color.
    static var inkLightHover = fromResource(named: "Ink Light Hover")
    /// Zuper Ink Normal color.
    static var inkNormal = fromResource(named: "Ink Normal")
    /// Zuper Ink Normal Active color.
    static var inkNormalActive = fromResource(named: "Ink Normal Active")
    /// Zuper Ink Normal Hover color.
    static var inkNormalHover = fromResource(named: "Ink Normal Hover")

    // MARK: - Orange
    /// Zuper Orange Dark color.
    static var orangeDark = fromResource(named: "Orange Dark")
    /// Zuper Orange Dark Active color.
    static var orangeDarkActive = fromResource(named: "Orange Dark Active")
    /// Zuper Orange Dark Hover color.
    static var orangeDarkHover = fromResource(named: "Orange Dark Hover")
    /// Zuper Orange Light color.
    static var orangeLight = fromResource(named: "Orange Light")
    /// Zuper Orange Light Active color.
    static var orangeLightActive = fromResource(named: "Orange Light Active")
    /// Zuper Orange Light Hover color.
    static var orangeLightHover = fromResource(named: "Orange Light Hover")
    /// Zuper Orange Normal color.
    static var orangeNormal = fromResource(named: "Orange Normal")
    /// Zuper Orange Normal Active color.
    static var orangeNormalActive = fromResource(named: "Orange Normal Active")
    /// Zuper Orange Normal Hover color.
    static var orangeNormalHover = fromResource(named: "Orange Normal Hover")

    // MARK: - Product
    /// Zuper Product Dark color.
    static var productDark = fromResource(named: "Product Dark")
    /// Zuper Product Dark Active color.
    static var productDarkActive = fromResource(named: "Product Dark Active")
    /// Zuper Product Dark Hover color.
    static var productDarkHover = fromResource(named: "Product Dark Hover")
    /// Zuper Product Light color.
    static var productLight = fromResource(named: "Product Light")
    /// Zuper Product Light Active color.
    static var productLightActive = fromResource(named: "Product Light Active")
    /// Zuper Product Light Hover color.
    static var productLightHover = fromResource(named: "Product Light Hover")
    /// Zuper Product Normal color.
    static var productNormal = fromResource(named: "Product Normal")
    /// Zuper Product Normal Active color.
    static var productNormalActive = fromResource(named: "Product Normal Active")
    /// Zuper Product Normal Hover color.
    static var productNormalHover = fromResource(named: "Product Normal Hover")

    // MARK: - Red
    /// Zuper Red Dark color.
    static var redDark = fromResource(named: "Red Dark")
    /// Zuper Red Dark Active color.
    static var redDarkActive = fromResource(named: "Red Dark Active")
    /// Zuper Red Dark Hover color.
    static var redDarkHover = fromResource(named: "Red Dark Hover")
    /// Zuper Red Light color.
    static var redLight = fromResource(named: "Red Light")
    /// Zuper Red Light Active color.
    static var redLightActive = fromResource(named: "Red Light Active")
    /// Zuper Red Light Hover color.
    static var redLightHover = fromResource(named: "Red Light Hover")
    /// Zuper Red Normal color.
    static var redNormal = fromResource(named: "Red Normal")
    /// Zuper Red Normal Active color.
    static var redNormalActive = fromResource(named: "Red Normal Active")
    /// Zuper Red Normal Hover color.
    static var redNormalHover = fromResource(named: "Red Normal Hover")
    
    // MARK: - Indico
    /// Zuper Indico Dark color.
    static var indicoDark = fromResource(named:"Indico Dark Hover")
    /// Zuper Indico Dark Hover color.
    static var indicoDarkHover = fromResource(named:"Indico Dark")
    /// Zuper Indico Light color.
    static var indicoLight = fromResource(named:"Indico Light")
    /// Zuper Indico Light Active color.
    static var indicoLightActive = fromResource(named:"Indico Light Active")
    /// Zuper Indico Light Hover color.
    static var indicoLightHover = fromResource(named:"Indico Light Hoverr")
    /// Zuper Indico Normal color.
    static var indicoNormal = fromResource(named:"Indico Normal")
    /// Zuper Indico Normal Hover color.
    static var indicoNormalHover = fromResource(named:"Indico Normal Hover")

    // MARK: - White
    /// Zuper White color.
    static var whiteNormal = fromResource(named: "White")
    /// Zuper White Darker color.
    static var whiteDarker = fromResource(named: "White Darker")
    /// Zuper White Lighter color.
    static var whiteLighter = fromResource(named: "White Lighter")
    
    // MARK: - Icon
    /// Zuper Icon Primary color.
    static var iconPrimary = fromResource(named:"Icon Primary")
    /// Zuper Icon Primary color.
    static var iconSecondary = fromResource(named:"Icon Secondary")
}
